appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: L5As+g9gBhaFhbX5kMF9LmeCp4GbjeA7X5DaufeTblO9H+yzakdSmSjlBPTIRLqaqPxtOEwWvPM7io8zui1H5KMXu0nXqktdKFk600suhPSNo0uFRT2Vb5c/N3FMrifvKtcEHHk7fF5Ve23d7/qLLnt/8YDjvafttzjPHhAwC7wdBTuZ7zzKrkv7EB8IqPWYSe9Ie6z+itVQMil3QzedudcAZXDsU/nh41KcKtux8SzEyQYxxF2sXSO+UoXYE+z/FOG3kULR4qdeYAYyDnPKEKzyUDmUb8zoodP2i4VY5sToQZ5MqcpCPWy52C1CmycuzomgUtkPX2xzhiUmF5QImTIbq7fpZHZP++v9rj1eZQLOFcKi3MQbVVbm9+r9h86gVOPjypdYg7QCgGp5DRSbjLNO3/cuWIWbc3BtB/a5QE7VbPfAFmpCMeHUb9Fm0tPSQwK5ZFaE1BtzJCdWJwf1gOPMCz66lDPP/FjCowWG4W+zoADQGHxfRoIYvmOT7cI6mbtrSYT9hPW/rziSeNzr8glJtpEo+Qi9zPHEH1+ko6S4Lji4bDIHeNGCw/ZQyC8qKuVb7eRpr1L6yGF2ay4uuDtfYwZJPToB7mBJf/nOFYbPgb9QD4P7am5ctU6LxmqQ7IqdrHiX8H6JbbeaVngpbzIem8J0y+CtJIVLdION0sY=
